[book]
authors = ["Arindam Das"]
language = "en"
src = "src"
title = "Comprehending Linux"

[output.html]
git-repository-url = "https://github.com/arindas/comprehending-linux/"
default-theme = "light"
mathjax-support = true

[output.html.fold]
enable = true
level = 1     # the depth to start folding
